INSERT INTO dacha_user (id, avatar_url, password, role, username) VALUES (1, '/images/dasha.jpg', 'user', 'USER', 'user');
INSERT INTO dacha_user (id, avatar_url, password, role, username) VALUES (777, '/images/chuck.jpg', 'admin', 'ADMIN', 'admin');


INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9991, 'Автор', 'BLOG', null, '2021-03-04', null, null, '/images/blog-07.jpg', null, 'Romantic Restaurant!', 'Best places for Wine!', 'name1', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9992, 'Автор', 'BLOG', null, '2021-03-04', null, null, '/images/blog-06.jpg', null, 'Blog text preview', 'Spring...Spring...', 'name2', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9993, 'Автор', 'BLOG', null, '2021-03-04', null, null, '/images/blog-04.jpg', null, 'Blog text preview', 'Test Blog Post', 'name3', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9994, 'Автор', 'BLOG', null, '2021-03-04', null, null, '/images/blog-12.jpg', null, 'Blog text preview!', 'Sorry, now site is a bunch of memes', 'name4', 20);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9995, 'Автор', 'BLOG', null, '2021-03-04', null, null, '/images/blog-14.jpg', null, 'Blog text preview!', 'Come with friends', 'name5', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9996, 'Автор', 'BLOG', null, '2021-03-04', null, null, '/images/blog-15.jpg', null, 'Blog text preview', 'You will never forget this dinner', 'name6', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9997, 'Автор', 'BLOG', null, '2021-02-04', null, null, '/images/blog-11.jpg', null, 'Blog text preview', 'Our waiters are awesome', 'name7', 15);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9998, 'Автор', 'BLOG', null, '2021-02-03', null, null, '/images/blog-10.jpg', null, 'Blog text preview', 'New youtube video!', 'name8', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (9999, 'Автор', 'BLOG', null, '2021-03-04', null, null, '/images/remi.jpg', null, 'I am a mouse', 'Best Chef in France', 'name9', 10);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (99911, 'Автор', 'ABOUT', null, '2021-03-04', null, null, '/images/intro-01.jpg', null, 'Phasellus lorem enim, luctus ut velit eget, con-vallis egestas eros.', 'Романтичный ресторан', 'intro1', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (99912, 'Автор', 'ABOUT', null, '2021-03-04', null, null, '/images/intro-02.jpg', null, 'Aliquam eget aliquam magna, quis posuere risus ac justo ipsum nibh urna', 'Изысканная еда', 'intro2', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (99913, 'Автор', 'ABOUT', null, '2021-03-04', null, null, '/images/intro-04.jpg', null, 'Sed ornare ligula eget tortor tempor, quis porta tellus dictum.', 'Красные вина которые вы любите', 'intro3', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (99914, 'Автор', 'EVENT', null, '2021-03-04', 'background-image: url(/images/bg-event-01.jpg)', '14 марта в 18:00', 'background-image: url(/images/event-01.jpg)', null, 'Phasellus lorem enim, luctus ut velit eget, con-vallis egestas eros.', 'Винные вечера на Даче', 'event1', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (99915, 'Автор', 'EVENT', null, '2021-03-04', 'background-image: url(/images/bg-event-02.jpg)', '8 марта целый день', 'background-image: url(/images/event-02.jpg)', null, 'Aliquam eget aliquam magna, quis posuere risus ac justo ipsum nibh urna', 'Выступление итальянского музыканта', 'event2', 0);
INSERT INTO blog_post (id, author, category, content, create_date, event_background_image_url, event_date_time, image_url, modify_date, preview_text, title, url_title, views_count) VALUES (99916, 'Приколист', 'EVENT', null, '2021-03-04', 'background-image: url(/images/bg-event-04.jpg)', 'когда-нибудь', 'background-image: url(/images/event-06.jpg)', null, 'Sed ornare ligula eget tortor tempor, quis porta tellus dictum.', 'Дегустация Рибая', 'event3', 0);


